# Automatically generated by configure - do not modify
SRC_PATH=/home/sl3dg3/Documents/focs/afl/qemu_mode/qemu-2.10.0/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
